version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - "3000:3000"
    external_links:
      - databases:mysql
networks:
  default:
    name: nginx-proxy